export const LOGIN = '[AUTH] LOGIN';
export const LOGIN_START = '[AUTH] LOGIN START';
export const LOGIN_FAILED = '[AUTH] LOGIN FAILED';
export const LOGOUT = '[AUTH] LOGOUT';

export const REGISTER = '[AUTH] REGISTER';
export const REGISTER_START = '[AUTH] REGISTER_START';
export const REGISTER_FAILED = '[AUTH] REGISTER_FAILED';

export const FORGOT = '[AUth] FORGOT';
export const FORGOT_START = '[AUTH] FORGOT_START';
export const FORGOT_FAILED = '[AUTH] FORGOT_FAILED';

export const INVITATION = 'INVITATION';

export const EMAIL_VERIFICATION_START = '[AUTH] EMAIL_VERIFICATION_START';
export const EMAIL_VERIFICATION = '[AUth] EMAIL_VERIFICATION';
export const EMAIL_VERIFICATION_FAILED = '[AUTH] EMAIL_VERIFICATION_FAILED';

export const RECOVERY_START = '[AUTH] RECOVERY_START';
export const RECOVERY = '[AUth] RECOVERY';
export const RECOVERY_FAILED = '[AUTH] RECOVERY_FAILED';

