export const MEMBER_LIST_START = '[MEMBER] MEMBER_LIST_START';
export const MEMBER_LIST = '[MEMBER] MEMBER_LIST';
export const MEMBER_LIST_FAILED = '[MEMBER] MEMBER_LIST_FAILED';

export const MEMBER_SHOW_START = '[MEMBER] MEMBER_SHOW_START';
export const MEMBER_SHOW = '[MEMBER] MEMBER_SHOW';
export const MEMBER_SHOW_FAILED = '[MEMBER] MEMBER_SHOW_FAILED';
export const RESET_MEMBER_SHOW = '[MEMBER] RESET_MEMBER_SHOW';
